apiVersion: v1

kind: Secret
metadata:
  name: telegraf-secrets
type: Opaque
stringData:
  INFLUXDB_DB: k8s_demo
  INFLUXDB_URL: http://140.92.152.61:8086
  INFLUXDB_USER: k8s
  INFLUXDB_USER_PASSWORD: "1234"

