apiVersion: v1

kind: Secret
metadata:
  name: telegraf-secrets
type: Opaque
stringData:
  INFLUXDB_DB: databaseName
  INFLUXDB_URL: http://<influxdb's ip>:8086
  INFLUXDB_USER: username
  INFLUXDB_USER_PASSWORD: "password"

